### PR TITLE
added rudimentary car calculator

### PR DESCRIPTION
**Pull request by JackDapid**
- added rudimentary car calculator, currently only working with average car CO2, but will add better calculation with choices already present

### CODE REVIEW

**Review by NicolasZanotti — APPROVED** [review]

**Comment by F-Ruxton** [comment]
Looks good so far @JackDapid Are you planning to add the details in this PR or a future one?

**Comment by F-Ruxton** [comment]
Cherry-picked 371c299884d9169ae97cd5da36b0d66f3d941b55 from train_calculator branch

**Comment by JackDapid** [comment]
How do we proceed on these, this and others are open now since several days. Should I merge as soon one approval is there? Or what is the procedure we want to use?

**Review by F-Ruxton — APPROVED** [review]
@JackDapid I've merged the latest changes from main. If you're intending to refine the calculator in a subsequent PR then I'm happy that this PR can be merged now

**Pull request merged**
