### PR TITLE
Comparison calculator

### PR DESCRIPTION
**Pull request by JackDapid**
- creating CO2 equivalent comparisons:

```
{
  "comparisons": [
    {
      "comparison": "Swiss capita equivalent",
      "value": 1,
      "description": "This is equivalent to how much CO2 1.0 average Swiss person cause per year."
    },
    {
      "comparison": "Swiss grey emissions capita equivalent",
      "value": 0.47058816,
      "description": "This is equivalent to how much CO2 0.47058816 average Swiss person (including grey emissions) cause per year."
    },
    {
      "comparison": "Swiss Tree equivalent",
      "value": 512,
      "description": "This is equivalent to how much CO2 512.0 average Swiss beech trees bind per year."
    },
    {
      "comparison": "Swiss Beef equivalent",
      "value": 512,
      "description": "This is equivalent to how much CO2 is caused by the production of 512.0 kg Swiss beef."
    }
  ]
}
```

### CODE REVIEW

**Comment by kjp** [comment]
I think #12 can be closed

**Comment by JackDapid** [comment]
How do we proceed on these, this and others are open now since several days. Should I merge as soon one approval is there? Or what is the procedure we want to use?

**Review by NicolasZanotti — APPROVED** [review]
Didn't go into much detail here with my review. @F-Ruxton has a better understanding than I do. 👍

IMO, at this stage of the project, you can merge any pull request that is open for too long.

**Comment by F-Ruxton** [comment]
Resolved merged commits after landing #15. Also did some tidying up and added ability to request specific comparisons

**Review by F-Ruxton — APPROVED** [review]

**Pull request merged**
