### PR TITLE
Create module interface class and cost aggregator

### PR DESCRIPTION
**Pull request by F-Ruxton**
Adds classes `ModuleInterface` and `ModuleInterfaces` to replace functions `interface`, `request`, `response`. This approach provides more structure to the definition of calculators/modules. This feeds into Karolos' work on `cost_aggregator`, which I've included and updated to use `ModuleInterfaces`, making it more generic:

- As discussed for the MVP purposes `ModuleInterface` includes a callback `get_total_carbon_kg` which takes the calculator's response and returns a single number for use in `cost_aggregator`. Going forwards this can be replaced with something more intelligent.
- Added a function to collect all validation errors to `cost_aggregator` and raise them in one go.
- Include complete responses from individual calculators for presentation an itemised breakdown.

### CODE REVIEW

**Comment by kjp** [comment]
Thanks @F-Ruxton ; this is very nice!

I was going to comment on the uniformisation of computing the total carbon emissions in kg but meanwhile you added `get_total_carbon_kg`. For me it's good to go!

**Review by kjp — APPROVED** [review]
All good from my pov.

**Comment by kjp** [comment]
#12 can be closed

**Comment by F-Ruxton** [comment]
Thanks for the review @kjp good to hear you're ok with the additions to your work

**Review by NicolasZanotti — APPROVED** [review]

**Pull request merged**
